# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
cache: packages
warnings_are_errors: false
r_packages:
  - covr
after_success:
  - Rscript -e 'library(covr); codecov()'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true